const SECRET_WORDS = [
    // ====== CONTES DE FÉES (Παραμύθια - 30) ======
    { word: "CENERENTOLA", hint: "Una fanciulla perde una scarpetta di vetro al ballo prima di mezzanotte." },
    { word: "CAPPUCCETTO ROSSO", hint: "Una bambina con un mantello scarlatto visita la nonna nel bosco." },
    { word: "BIANCANEVE", hint: "Una principessa vive con sette amici minatori e morde un frutto avvelenato." },
    { word: "LA BELLA ADDORMENTATA", hint: "Una giovane si punge con un fuso e dorme cento anni." },
    { word: "POLLICINO", hint: "Un bimbo minuscolo lascia sassolini bianchi per ritrovare la strada." },
    { word: "HANSEL E GRETEL", hint: "Due fratelli scoprono una casina di dolciumi nella foresta." },
    { word: "RAPERONZOLO", hint: "Una fanciulla rinchiusa in una torre ha una treccia dorata molto lunga." },
    { word: "IL BRUTTO ANATROCCOLO", hint: "Un piccolo volatile diverso diventa un magnifico cigno." },
    { word: "LA SIRENETTA", hint: "Una creatura marina con coda squamosa sogna di camminare sulla terraferma." },
    { word: "IL RE RANOCCHIO", hint: "Un anfibio verde aiuta una principessa a recuperare una palla caduta in una fonte." },
    { word: "RICCIOLI D'ORO", hint: "Una bimba entra nella casa di tre orsi e assaggia la loro zuppa." },
    { word: "I TRE PORCELLINI", hint: "Fratelli costruiscono rifugi di paglia, legno e mattoni contro un soffio potente." },
    { word: "IL GATTO CON GLI STIVALI", hint: "Un felino furbo porta scarpe eleganti per aiutare un giovane." },
    { word: "MIGNOLINA", hint: "Una fanciulla alta un pollice nata in un fiore incontra un maggiolino." },
    { word: "LA REGINA DELLE NEVI", hint: "Una sovrana dal potere glaciale crea un palazzo di ghiaccio e scaglia fiocchi." },
    { word: "ALADINO", hint: "Un ragazzo trova un tappeto volante e una lampada con un genio." },
    { word: "IL LIBRO DELLA GIUNGLA", hint: "Un cucciolo d'uomo cresciuto tra i lupi gira nella foresta con un orso e una pantera." },
    { word: "PINOCCHIO", hint: "Un burattino di legno il cui naso si allunga quando mente." },
    { word: "PETER PAN", hint: "Un ragazzo che vola con polvere fatata e non vuole mai crescere." },
    { word: "L'OMINO DI PAN DI ZENZERO", hint: "Un dolcetto che prende vita e scappa attraverso il paese." },
    { word: "JACK E IL FAGIOLO MAGICO", hint: "Un giovane scambia una mucca per semi che crescono fino al cielo." },
    { word: "LA BELLA E LA BESTIA", hint: "Una fanciulla intelligente spezza l'incantesimo di un principe dall'aspetto mostruoso." },
    { word: "IL CAVALLINO GOBBO", hint: "Un piccolo destriero dalla groppa ricurva aiuta un contadino a compiere imprese." },
    { word: "LA PRINCIPESSA SUL PISELLO", hint: "Una giovane dalla pelle sensibile sente un minuscolo legume sotto venti materassi." },
    { word: "I MUSICANTI DI BREMA", hint: "Animali anziani partono per la città per diventare artisti e incontrano ladri." },
    { word: "IL LUPO E I SETTE CAPRETTI", hint: "Un animale grigio cerca di entrare in casa addolcendo la voce." },
    { word: "IL VASCELLO FANTASMA", hint: "Una nave maledetta condannata a errare sui mari con un capitano spettrale." },
    { word: "PUFF IL DRAGO", hint: "Una canzone su una creatura che vive in una caverna e soffia fuoco." },
    { word: "LA FATINA DEI DENTI", hint: "Una creatura alata raccoglie le piccole perle bianche che i bambini perdono sotto il cuscino." },
    { word: "IL GIGANTE DI ZERALDA", hint: "Un orco cattura bambini e incontra una bimba che sa cucinare." },

    // ====== TELEVISIONE PER BAMBINI (Παιδική Τηλεόραση - 25) ======
    { word: "SPONGEBOB", hint: "Un personaggio giallo vive in un ananas in fondo al mare e prepara crocchette di granchio." },
    { word: "DORA L'ESPLORATRICE", hint: "Una bimba viaggia con uno zaino e una mappa e chiede aiuto per le sue avventure." },
    { word: "PEPPA PIG", hint: "Una maialina adora saltare nelle pozzanghere con suo fratello George." },
    { word: "SAM IL POMPIERE", hint: "Un coraggioso soccorritore in uniforme rossa aiuta gli abitanti di una cittadina." },
    { word: "LE MISTERIOSE CITTÀ D'ORO", hint: "Un cartone animato d'avventura segue ragazzi alla ricerca di tesori." },
    { word: "WINNIE THE POOH", hint: "Un orsetto giallo ghiotto di miele vive in un bosco con i suoi amici di pezza." },
    { word: "TROTRO", hint: "Un piccolo asino grigio birichino che spesso si rifiuta di obbedire." },
    { word: "ORSETTO BRUNO", hint: "Un tenero plantigrado vive piccole avventure quotidiane con i genitori." },
    { word: "T'CHOUPI", hint: "Un giovane pinguino curioso scopre il mondo con il suo pupazzo." },
    { word: "NODDY", hint: "Un burattino di legno con un berretto rosso guida un taxi nel Paese dei Balocchi." },
    { word: "I PUFFI", hint: "Minuscole creature blu vivono in un villaggio di funghi, inseguiti da un mago." },
    { word: "LUCKY LUKE", hint: "Un cowboy solitario che spara più veloce della sua ombra e insegue i banditi." },
    { word: "ASTERIX", hint: "Un piccolo guerriero gallico resiste ai romani grazie a una pozione che dona forza." },
    { word: "OBELIX", hint: "Il compagno forte e goloso del guerriero gallico, sempre pronto a trasportare menhir." },
    { word: "TINTIN", hint: "Un reporter con un ciuffo biondo gira il mondo col suo fedele cane bianco." },
    { word: "CAPITAN HADDOCK", hint: "Il marinaio collerico che ripete 'mille milioni di mille sabordi!'." },
    { word: "LA PIMPA", hint: "Una cagnolina a pois rossi vive avventure con i suoi amici animali." },
    { word: "MILO IL CONIGLIO", hint: "Un animaletto bianco curioso esplora il mondo con i suoi amici." },
    { word: "MASHA E ORSO", hint: "Una bimba dispettosa fa amicizia con un grosso plantigrado del bosco." },
    { word: "IL GRUFFALÒ", hint: "Un mostro del bosco spaventa gli altri animali ma ha paura di un piccolo topo." },
    { word: "PJ MASKS", hint: "Tre bambini indossano pigiami per diventare eroi notturni." },
    { word: "BING", hint: "Un coniglietto nero che vive piccole disavventure con i suoi amici." },
    { word: "PAW PATROL", hint: "Una squadra di cuccioli soccorritori guidati da un ragazzo di nome Ryder." },
    { word: "I DALTON", hint: "Una serie comica su quattro fratelli fuorilegge altissimi e litigiosi." },
    { word: "L'APE MAIA", hint: "Un animaletto volante a strisce gialle e nere lascia il suo nido per esplorare." },

    // ====== CANZONI PER BAMBINI (Παιδικά Τραγούδια - 20) ======
    { word: "FRA MARTINO", hint: "Una canzone che chiede se si dorme ancora e se le campane suonano." },
    { word: "STELLA STELLINA", hint: "Una ninnananna che invita un astro luminoso ad avvicinarsi al letto." },
    { word: "CI VUOLE UN FIORE", hint: "Una melodia che racconta come da un piccolo seme nasca una pianta profumata." },
    { word: "IL COCCODRILLO COME FA", hint: "Una canzone che si chiede come faccia un grosso rettile verde a parlare." },
    { word: "LA TARTARUGA", hint: "Una filastrocca su un animale lento con il guscio che va a passeggio." },
    { word: "SE SEI FELICE E TU LO SAI", hint: "Un brano in cui si battono le mani e si pestano i piedi se si è contenti." },
    { word: "WHISKEY IL RAGNETTO", hint: "Un minuscolo animale a otto zampe tesse la sua tela e sale sulla grondaia." },
    { word: "ALLA FIERA DELL'EST", hint: "Una canzone su un mercato dove si compra un topolino e poi un gatto." },
    { word: "NELLA VECCHIA FATTORIA", hint: "Una canzone dove gli animali emettono versi e fanno confusione in un cortile." },
    { word: "LA DANZA DEL SERPENTE", hint: "Un brano per muoversi in fila dietro un lungo tubo di carta che ondeggia." },
    { word: "CI SONO DUE COCCODRILLI", hint: "Una canzone buffa su due grossi rettili e un orango tango." },
    { word: "L'ELEFANTE SI DONDOLAVA", hint: "Un pachiderma gioca su una ragnatela e chiama altri amici." },
    { word: "QUARANTAQUATTRO GATTI", hint: "Un brano che parla di tanti felini domestici in fila per sei col resto di due." },
    { word: "IL VALZER DEL MOSCERINO", hint: "Una canzone su un insetto che balla con una zanzara." },
    { word: "LA BELLA LAVANDERINA", hint: "Una filastrocca su una giovane che fa il bucato e stende al sole." },
    { word: "GIRO GIRO TONDO", hint: "Un ballo in cerchio cantato dove tutti si tengono per mano e ruotano." },
    { word: "IL PINGUINO BELISARIO", hint: "Una canzone su un uccello marino in smoking che balla." },
    { word: "CARO GESÙ", hint: "Una canzone natalizia in cui un bambino scrive una lettera al cielo." },
    { word: "LA CANZONE DELL'AUTUNNO", hint: "Un brano che racconta delle foglie che cadono e del vento nella stagione fredda." },
    { word: "NINNA NANNA NINNA OH", hint: "Una nenia dolce per far addormentare i piccoli." },

    // ====== SCUOLA E MATERIALE (Σχολείο - 20) ======
    { word: "ZAINETTO", hint: "Una borsa portata sulle spalle dagli scolari per i libri." },
    { word: "ASTUCCIO", hint: "Un contenitore con cerniera per riporre penne e matite." },
    { word: "LAVAGNA", hint: "Una superficie scura appesa al muro su cui si scrive con il gessetto." },
    { word: "QUADERNO", hint: "Un insieme di fogli rilegati dove gli alunni prendono appunti." },
    { word: "RICREAZIONE", hint: "Il momento della giornata scolastica in cui si può uscire in cortile." },
    { word: "MAESTRA", hint: "Una signora che insegna a leggere e a far di conto ai bambini." },
    { word: "PENNA", hint: "Uno strumento per scrivere con inchiostro blu o nero." },
    { word: "GOMMA", hint: "Un oggettino di caucciù che cancella gli errori di matita." },
    { word: "TEMPERAMATITE", hint: "Un arnese con una lama per fare la punta ai lapis." },
    { word: "RIGHELLO", hint: "Una barretta graduata per misurare e tracciare linee dritte." },
    { word: "COMPASSO", hint: "Uno strumento a due braccia per disegnare cerchi perfetti." },
    { word: "COLLA", hint: "Una sostanza appiccicosa per unire fogli di carta." },
    { word: "PENNARELLO", hint: "Un tipo di penna a punta di feltro per colorare." },
    { word: "PASTELLI", hint: "Piccoli cilindri di cera colorata per riempire disegni." },
    { word: "BANCO", hint: "Il mobile con piano inclinato su cui gli alunni scrivono." },
    { word: "SCUOLA", hint: "L'edificio dove i bambini vanno ogni mattina per imparare." },
    { word: "COMPITI", hint: "Gli esercizi che i professori assegnano da fare a casa." },
    { word: "DETTATO", hint: "Un esercizio di ortografia in cui si scrivono parole pronunciate." },
    { word: "BIBLIOTECA", hint: "Una stanza silenziosa piena di scaffali di storie da leggere." },
    { word: "MENSA", hint: "Il locale dove gli studenti pranzano a mezzogiorno con un vassoio." },

    // ====== EROI E PERSONAGGI (Ήρωες - 25) ======
    { word: "SPIDER-MAN", hint: "Un giustiziere in costume da aracnide si arrampica sui muri lanciando ragnatele." },
    { word: "BATMAN", hint: "Il cavaliere oscuro protegge la sua città con gadget e un'ombra sinistra." },
    { word: "SUPERMAN", hint: "Un uomo fortissimo vola con un mantello rosso e teme le pietre verdi." },
    { word: "CAPITAN AMERICA", hint: "Un soldato con uno scudo rotondo difende la libertà dopo un siero." },
    { word: "HULK", hint: "Un gigante color smeraldo diventa potentissimo quando si arrabbia." },
    { word: "THOR", hint: "Il dio del tuono brandisce un martello magico e viaggia tra i mondi." },
    { word: "IRON MAN", hint: "Un inventore miliardario indossa un'armatura metallica volante piena di tecnologia." },
    { word: "ELSA", hint: "Una regina capace di creare ghiaccio e neve con un gesto della mano." },
    { word: "OLAF", hint: "Un pupazzo di neve incantato che sogna l'estate e gli abbracci caldi." },
    { word: "MOANA", hint: "Una giovane isolana naviga sull'oceano per restituire il cuore a una divinità." },
    { word: "ARIEL", hint: "La figlia minore del re del mare colleziona oggetti umani in una grotta." },
    { word: "SIMBA", hint: "Un giovane leone deve diventare il sovrano della savana dopo una tragedia." },
    { word: "MULAN", hint: "Una coraggiosa ragazza si veste da guerriero per difendere la patria." },
    { word: "BELLE", hint: "Una giovane intelligente che ama i libri spezza l'incantesimo di un principe." },
    { word: "POCAHONTAS", hint: "Una principessa nativa americana parla agli spiriti e protegge la natura." },
    { word: "MERLINO", hint: "Un vecchio mago barbuto consiglia il futuro re Artù con saggezza." },
    { word: "TARZAN", hint: "Un uomo cresciuto tra le scimmie si sposta urlando e aggrappandosi alle liane." },
    { word: "ALICE", hint: "Una bimba cade in una tana e incontra un cappellaio matto e una regina di cuori." },
    { word: "IL PICCOLO PRINCIPE", hint: "Un ragazzino biondo venuto da un asteroide chiede un disegno di un ovino." },
    { word: "YODA", hint: "Un piccolo essere verde rugoso insegna la saggezza ai cavalieri in una galassia lontana." },
    { word: "HARRY POTTER", hint: "Un giovane mago con gli occhiali frequenta una scuola di magia e combatte un mago oscuro." },
    { word: "FATA SMEMORINA", hint: "Una creatura alata con un bastoncino fatato aiuta una fanciulla a realizzare un desiderio." },
    { word: "PIPPI CALZELUNGHE", hint: "Una bambina con le trecce rosse e lentiggini vive da sola in una villa colorata." },
    { word: "CIPOLLINO", hint: "Un ragazzo a forma di bulbo commestibile che lotta contro le ingiustizie nel mondo vegetale." },
    { word: "GERONIMO STILTON", hint: "Un topo giornalista che vive avventure scritte nei suoi libri." },

    // ====== ANIMALI (Ζώα - 10) ======
    { word: "ELEFANTE", hint: "Il più grande mammifero terrestre con proboscide e grandi orecchie." },
    { word: "GIRAFFA", hint: "Un animale dal collo lunghissimo maculato che bruca foglie di acacia." },
    { word: "COCCODRILLO", hint: "Un rettile dai denti aguzzi che vive nei fiumi e nelle paludi calde." },
    { word: "DELFINO", hint: "Un mammifero marino giocherellone che salta fuori dalle onde e fischia." },
    { word: "FARFALLA", hint: "Un insetto dalle ali colorate che si posa sui fiori dopo essere stato bruco." },
    { word: "CRICETO", hint: "Un piccolo roditore domestico dal pelo morbido che corre sulla ruota." },
    { word: "CONIGLIO", hint: "Un mammifero dalle lunghe orecchie che ama le carote e scava tane." },
    { word: "GATTO", hint: "Un felino domestico che fa le fusa, caccia i topi e si lava con la lingua." },
    { word: "CANE", hint: "Il miglior amico dell'uomo, fedele, che scodinzola e riporta la palla." },
    { word: "PESCE ROSSO", hint: "Un piccolo animale acquatico arancione che nuota in una boccia." },

    // ====== GIOCATTOLI E PASSATEMPI (Παιχνίδια - 10) ======
    { word: "BAMBOLA", hint: "Un giocattolo che somiglia a un neonato, da vestire e cullare." },
    { word: "MACCHININA TELECOMANDATA", hint: "Un piccolo veicolo radiocomandato che si dirige con una manopola." },
    { word: "LEGO", hint: "Mattoncini di plastica che si incastrano per costruire castelli o astronavi." },
    { word: "ALTALENA", hint: "Un seggiolino sospeso con corde al parco dove si dondola avanti e indietro." },
    { word: "SCIVOLO", hint: "Un piano inclinato sull'area giochi su cui si scivola seduti." },
    { word: "BIGLIE", hint: "Piccole sfere di vetro colorato che si fanno rotolare in un percorso disegnato." },
    { word: "TRENO ELETTRICO", hint: "Un circuito in miniatura con vagoni che corrono su binari alimentati." },
    { word: "GIOCO DA TAVOLO", hint: "Un passatempo da fare in gruppo con un tabellone, dadi e pedine." },
    { word: "COSTUME", hint: "Un travestimento per trasformarsi in principessa, pirata o supereroe." },
    { word: "LIBRO", hint: "Un oggetto pieno di storie e figure che si sfoglia prima di dormire." },

    // ====== CIBO E DOLCI (Φαγητά - 10) ======
    { word: "CIOCCOLATO", hint: "Una golosità marrone e dolce che si scioglie in bocca, fatta con fave." },
    { word: "CARAMELLA", hint: "Un piccolo dolcino zuccherato che pizzica o addolcisce la lingua, spesso colorato." },
    { word: "GELATO", hint: "Un dessert freddo che si lecca in cono, d'estate, alla fragola o alla vaniglia." },
    { word: "CRÊPE", hint: "Una sottile cialda di pastella cotta in padella, farcita con zucchero o marmellata." },
    { word: "CIALDA", hint: "Un biscotto croccante con motivi a nido d'ape, spesso spolverato di zucchero a velo." },
    { word: "BRIOCHE", hint: "Un dolce lievitato soffice a forma di mezzaluna, buono a colazione." },
    { word: "MARMELLATA", hint: "Una conserva di frutta cotta, spalmabile sul pane." },
    { word: "YOGURT", hint: "Un latticino cremoso, bianco o alla frutta, da mangiare al cucchiaio." },
    { word: "BISCOTTO", hint: "Un pasticcino secco da inzuppare nel latte o nel tè." },
    { word: "SCIROPPO", hint: "Un liquido concentrato e zuccherino da diluire in acqua per una bibita." }
];