
const WORDS_EN = [
    // ====== FAIRYTALES & CLASSICS ======
    { word: "CINDERELLA", hint: "A girl who leaves behind a glass slipper at the royal ball before midnight." },
    { word: "PINOCCHIO", hint: "A friendly wooden puppet whose nose grows longer whenever he tells a lie." },
    { word: "PETER PAN", hint: "The boy from Neverland who refuses to grow up and flies with fairy dust." },
    { word: "RAPUNZEL", hint: "A beautiful princess with very long, magical golden hair trapped in a tall tower." },
    { word: "ALADDIN", hint: "A poor street boy who finds a flying carpet and a magical blue genie." },
    { word: "ALICE", hint: "A girl who falls down a rabbit hole into a bizarre world with a talking cat and a mad hatter." },
    { word: "BEAUTY AND THE BEAST", hint: "A story about a kind girl who falls in love with a scary monster in a castle." },
    { word: "SLEEPING BEAUTY", hint: "A princess who pricks her finger on a spinning wheel and falls into a deep nap for a hundred years." },
    { word: "HANSEL AND GRETEL", hint: "Two siblings who get lost in the woods and find a house made entirely of sweet candy." },
    { word: "LITTLE RED RIDING HOOD", hint: "A young girl wearing a colorful cape who walks through the forest to visit her sick grandmother." },
    { word: "THE THREE LITTLE PIGS", hint: "Animal brothers who build houses out of straw, wood, and bricks to hide from a big wolf." },
    { word: "CASTLE", hint: "A massive stone building with high walls and towers where kings and queens live." },
    { word: "PIRATE", hint: "A sailing explorer from old stories who wears an eyepatch and hunts for buried gold." },
    { word: "WIZARD", hint: "A magical man in stories who wears a pointy hat and casts spells with a wand." },

    // ====== YOUTUBERS & TIKTOKERS ======
    { word: "MRBEAST", hint: "A famous content creator known for giving away millions of dollars and huge challenges." },
    { word: "RYAN", hint: "A young boy who became famous on the internet for unboxing and reviewing cool toys." },
    { word: "DANTDM", hint: "A famous British gamer with blue hair who loves playing Minecraft." },
    { word: "PRESTON", hint: "A popular gaming content creator known for playing blocks and doing hide-and-seek challenges." },
    { word: "UNSPEAKABLE", hint: "A gaming creator who wears a green frog icon and fills houses with plastic balls." },
    { word: "BLIPPI", hint: "A joyful adult creator wearing a bright orange and blue hat who teaches toddlers about trucks." },

    // ====== SHOWS & CARTOONS ======
    { word: "POKEMON", hint: "Animated pocket monsters that trainers catch in small red and white balls to battle." },
    { word: "PAW PATROL", hint: "A group of heroic rescue puppies led by a tech-savvy boy named Ryder." },
    { word: "BLUEY", hint: "A lovable six-year-old Blue Heeler dog who goes on fun adventures with her family in Australia." },
    { word: "COCOMELON", hint: "A highly popular animated 3D streaming show for toddlers featuring nursery rhymes." },
    { word: "PEPPA PIG", hint: "A cheeky little pink animal who loves jumping up and down in muddy puddles." },
    { word: "SESAME STREET", hint: "A classic educational show featuring muppets like Elmo, Big Bird, and a cookie lover." },
    { word: "NINJAGO", hint: "A Lego-themed animated series about warriors mastering the elements to protect their world." },
    { word: "MIRACULOUS", hint: "A superhero series about Paris teenagers who transform into Ladybug and Cat Noir." },
    { word: "SPONGEBOB", hint: "A yellow, square cartoon character who lives in a pineapple under the ocean." },
    { word: "SCOOBY DOO", hint: "A scared brown dog who loves snacks and solves spooky mysteries with his human friends." },
    { word: "TOM AND JERRY", hint: "A classic cartoon duo featuring a grey cat constantly chasing a clever brown mouse." },
    { word: "LOONEY TUNES", hint: "Classic animated shorts featuring funny characters like Bugs Bunny and Daffy Duck." },
    { word: "TEEN TITANS", hint: "A group of young comic book superheroes like Robin and Cyborg living together and protecting their city." },
    { word: "THE SIMPSONS", hint: "A famous long-running animated show about a funny yellow family living in Springfield." },
    { word: "POPEYE", hint: "A classic sailor character who gets super strength whenever he eats a can of spinach." },

    // ====== MOVIES & POPULAR CHARACTERS ======
    { word: "NEMO", hint: "A brave clownfish dad swims across the entire ocean to find his missing son." },
    { word: "OLAF", hint: "A magical snowman built by two royal sisters who really loves warm hugs." },
    { word: "ELSA", hint: "An Ice Queen who sings a famous song about letting go while creating a frozen palace." },
    { word: "SHREK", hint: "A grumpy green ogre who wants peace in his swamp but ends up rescuing a princess with a talking donkey." },
    { word: "BARBIE", hint: "A world-famous fashion doll who lives in a pink dreamhouse and can work any job imaginable." },
    { word: "MINIONS", hint: "Small, yellow cylindrical creatures who speak a funny language and serve a villain named Gru." },
    { word: "BUZZ LIGHTYEAR", hint: "A space ranger toy who famously shouts his catchphrase about flying to infinity and beyond." },
    { word: "LIGHTNING MCQUEEN", hint: "A red racing car with the number 95 who learns about friendship in Radiator Springs." },
    { word: "MOANA", hint: "A village chief's daughter who sails across the ocean with a demigod to restore a magical heart." },
    { word: "SIMBA", hint: "A young lion cub who cannot wait to be king after fleeing his home savanna." },
    { word: "MICKEY MOUSE", hint: "The iconic cartoon character with round black ears who wears red shorts and yellow shoes." },
    { word: "WEDNESDAY", hint: "A spooky, smart girl from the Addams family who attends Nevermore Academy and does a viral dance." },
    { word: "GROGU", hint: "A cute green alien baby with huge ears from Star Wars who uses the Force." },
    { word: "FIONA", hint: "A princess who turns into a green ogre when the sun goes down." },
    { word: "WOODY", hint: "A brave cowboy toy with a pull-string who is best friends with a space ranger." },
    { word: "GRINCH", hint: "A furry green creature who learns to love Christmas and a happy village." },
    { word: "TARZAN", hint: "A man raised by apes in the jungle who swings on vines and wears a loincloth." },
    { word: "MINNIE", hint: "Mickey's favorite friend who wears a red or pink polka dot dress with a big bow." },
    { word: "DONALD DUCK", hint: "A funny white bird character with a blue sailor hat who gets angry very easily." },
    { word: "THE LION KING", hint: "A spectacular animated movie about a young cub named Simba who learns about the circle of life." },

    // ====== SUPERHEROES ======
    { word: "SPIDERMAN", hint: "A hero who swings from city buildings using webs and wears a red and blue suit." },
    { word: "BATMAN", hint: "The Dark Knight of Gotham City who uses high-tech gadgets and a special car to protect the city." },
    { word: "SUPERMAN", hint: "An alien hero from Krypton who can fly, has x-ray vision, and is weak to green rocks." },
    { word: "IRON MAN", hint: "A rich genius superhero who builds a flying metal armor suit powered by an arc reactor." },
    { word: "HULK", hint: "A giant green superhero who gets incredibly strong whenever he becomes angry." },
    { word: "THOR", hint: "A powerful prince who commands lightning and throws a magical heavy hammer." },
    { word: "GROOT", hint: "A friendly tree-like alien hero who can only say three specific words about himself." },

    // ====== BOOKS & STORIES ======
    { word: "HARRY POTTER", hint: "A young orphan boy who discovers on his eleventh birthday that he is a magical wizard." },
    { word: "PERCY JACKSON", hint: "A modern teenager who discovers he is actually the demigod son of Poseidon." },
    { word: "MATILDA", hint: "A brilliant little girl with special mind powers who loves reading and faces a mean headmistress." },
    { word: "WIMPY KID", hint: "Greg Heffley writes and draws about his hilarious middle school struggles in a famous diary series." },
    { word: "DOG MAN", hint: "A comic book series about a hero who is part canine and part police officer." },
    { word: "GRUFFALO", hint: "A clever little mouse invents a scary monster with tusks and purple prickles to frighten predators." },

    // ====== PROVERBS & SAYINGS ======
    { word: "DOCTOR", hint: "An apple a day keeps this helpful person away." },
    { word: "TIME", hint: "Flying like an arrow, this precious thing stops for nobody." },
    { word: "PENNY", hint: "Saved is a coin earned, meaning you should protect your small money." },
    { word: "FRIENDS", hint: "Birds of a feather flock together, meaning people with common interests become close." },
    { word: "PRACTICE", hint: "Doing something over and over makes perfect, helping you master a new skill." },
    { word: "HONESTY", hint: "Telling the truth is always the best policy." },
    { word: "KNOWLEDGE", hint: "Learning things gives you power, because understanding the world makes you strong." },
    { word: "ACTION", hint: "Doing things speaks louder than just talking about them." },
    { word: "BETTER LATE THAN NEVER", hint: "An expression meaning it is wiser to arrive or finish something behind schedule than not to do it at all." },
    { word: "NO PAIN NO GAIN", hint: "A famous saying that means you have to work really hard and face difficulties to achieve success." },
    { word: "EASY COME EASY GO", hint: "A phrase about things or money that are won quickly but can also be lost just as fast." },
    { word: "TWO WRONGS DONT MAKE A RIGHT", hint: "A lesson teaching kids that hurting someone back just because they hurt you first is not correct." },

    // ====== CHILDREN'S SONGS ======
    { word: "BABY SHARK", hint: "A super popular tune about a family of ocean animals with a very catchy 'doo doo doo' sound." },
    { word: "TWINKLE TWINKLE", hint: "A classic lullaby about a tiny, bright diamond shining high up in the dark night sky." },
    { word: "OLD MACDONALD", hint: "A famous song about a farmer who keeps cows, chicks, and ducks on his land." },
    { word: "THE WHEELS ON THE BUS", hint: "A fun song describing a large city vehicle going round and round all through the town." },
    { word: "IF YOU ARE HAPPY", hint: "A cheerful melody where kids are asked to clap their hands and stomp their feet if they feel good." },

    // ====== GAMES & POP CULTURE ======
    { word: "MINECRAFT", hint: "A sandbox video game where players mine blocks and build anything they want while avoiding Creepers." },
    { word: "ROBLOX", hint: "An online platform where kids can create their own custom games and hang out with avatars." },
    { word: "FORTNITE", hint: "A colorful game where players drop from a flying bus, build structures, and dance." },
    { word: "SONIC", hint: "A bright blue hedgehog who can run faster than the speed of sound and collects golden rings." },
    { word: "MARIO", hint: "A friendly Italian plumber with a red cap who jumps on mushrooms to rescue a princess." },
    { word: "PIKACHU", hint: "The most famous electric mouse character that shoots yellow lightning bolts." },
    { word: "AMONG US", hint: "A space game where crewmates complete tasks while trying to find the sneaky impostor." },
    { word: "CHESS", hint: "A smart board game with kings, queens, and knights where you try to trap the enemy king." },
    { word: "GAMER", hint: "A person who loves playing video games on a console, computer, or phone." },
    { word: "LEVEL", hint: "A specific stage or floor in a video game that you must complete to advance." },

    // ====== TOYS & HOBBIES ======
    { word: "SLIME", hint: "A gooey, stretchy colorful substance that kids love to squeeze and play with." },
    { word: "KITE", hint: "A light frame covered with paper or cloth that flies in the air on a string." },
    { word: "SKATEBOARD", hint: "A short, narrow board with small wheels at each end that you stand on to roll." },
    { word: "TEDDY BEAR", hint: "A soft toy animal stuffed with fluff that children love to cuddle in bed." },
    { word: "DOLL", hint: "A toy that looks like a small person or baby, often with hair you can brush." },
    { word: "BALLOON", hint: "A bright rubber bag filled with air or gas that floats and pops if poked." },
    { word: "PUZZLE", hint: "A game with many interlocking pieces that fit together to make a whole picture." },

    // ====== ANIMALS ======
    { word: "LION", hint: "The king of the jungle with a loud roar and a big, furry mane." },
    { word: "ELEPHANT", hint: "A huge gray animal with big, floppy ears and a long trunk." },
    { word: "MONKEY", hint: "A funny animal that loves eating yellow fruit and swinging from trees." },
    { word: "SHARK", hint: "A large ocean fish with sharp teeth and a dorsal fin that swims fast." },
    { word: "DOLPHIN", hint: "A highly intelligent sea creature that breathes air, smiles, and does flips out of waves." },
    { word: "DINOSAUR", hint: "A giant ancient creature that ruled the earth millions of years ago before disappearing." },
    { word: "BUTTERFLY", hint: "A beautiful insect with colorful wings that hatches from a caterpillar." },
    { word: "GIRAFFE", hint: "An extremely tall African animal with an incredibly long neck and brown spots." },
    { word: "PANDA", hint: "A cute black and white bear from China that loves chewing on green bamboo sticks." },
    { word: "OWL", hint: "A nocturnal bird with huge eyes that stays awake at night and says 'whoo'." },

    // ====== FOOD & TREATS ======
    { word: "MILK", hint: "Don't cry over spilled... (a healthy white drink that comes from cows)." },
    { word: "PIZZA", hint: "A round, hot dish cut into triangles, usually topped with cheese and tomato sauce." },
    { word: "ICECREAM", hint: "A very cold, sweet dessert you eat in a cone during summer." },
    { word: "BANANA", hint: "A long yellow fruit that you have to peel before eating." },
    { word: "BURGER", hint: "A round sandwich with a grilled meat patty, lettuce, cheese, and tomato inside a bun." },
    { word: "COOKIE", hint: "A sweet, baked flat treat often filled with chocolate chips, perfect with milk." },
    { word: "CUPCAKE", hint: "A tiny, individual sweet cake baked in a paper cup and topped with colorful frosting." },
    { word: "APPLE", hint: "A crunchy round fruit that can be red, green, or yellow, with seeds in the middle." },
    { word: "POPCORN", hint: "Salty white snacks made from heated corn kernels that you eat at the movie theater." },
    { word: "DONUT", hint: "A fried dough pastry shaped like a ring, often covered in sweet glaze or sprinkles." },

    // ====== SPACE & NATURE ======
    { word: "ASTRONAUT", hint: "A brave explorer who wears a special suit and travels in a rocket ship." },
    { word: "RAINBOW", hint: "A beautiful, colorful arch in the sky that appears right after it rains." },
    { word: "SUN", hint: "The big, bright yellow circle in the sky that warms us during the day." },
    { word: "MOON", hint: "The bright rocky sphere that glows in the night sky and circles our planet." },
    { word: "CLOUD", hint: "A fluffy white mass floating in the sky made of tiny drops of water." },
    { word: "FOREST", hint: "A large area covered with many tall trees, plants, and wild animals." },
    { word: "ROCKET", hint: "A powerful vehicle shaped like a tube used to blast off into outer space." },
    { word: "PLANET", hint: "A massive round object in space, like Earth or Mars, that travels around a star." },

    // ====== SCHOOL & DAILY LIFE ======
    { word: "PENCIL", hint: "A wooden tool with a dark tip used for writing or drawing, often with a pink eraser on top." },
    { word: "BACKPACK", hint: "A bag you carry on your shoulders to take your books to school." },
    { word: "BICYCLE", hint: "A vehicle with two wheels that you pedal to ride around the park." },
    { word: "SOCCER", hint: "A popular sport where two teams try to kick a round ball into a net without using hands." },
    { word: "GUITAR", hint: "A musical instrument with six strings that you pluck or strum to make sounds." },
    { word: "DANCE", hint: "Moving your body to the rhythm of a song or musical beat." },
    { word: "MAGIC", hint: "Entertaining tricks that look impossible, performed by someone with a wand or top hat." },
    { word: "ROBOT", hint: "A mechanical machine built by humans that can move and perform tasks automatically." }
];
