const WORDS_FR = [
    // ====== CONTES DE FÉES (Παραμύθια - 30) ======
    { word: "CENDRILLON", hint: "Une jeune fille perd une chaussure de verre au bal du château avant minuit." },
    { word: "LE PETIT CHAPERON ROUGE", hint: "Une enfant portant une coiffe de couleur vive rend visite à sa grand-mère dans les bois." },
    { word: "BLANCHE-NEIGE", hint: "Une princesse qui vit avec sept petits compagnons et croque un fruit empoisonné." },
    { word: "LA BELLE AU BOIS DORMANT", hint: "Une jolie jeune femme se pique le doigt sur un fuseau et dort cent ans." },
    { word: "LE PETIT POUCET", hint: "Un garçon minuscule perd des cailloux blancs pour retrouver son chemin dans la forêt." },
    { word: "HANSEL ET GRETEL", hint: "Un frère et une sœur découvrent une maison faite de sucreries au milieu des arbres." },
    { word: "RAIPONCE", hint: "Une demoiselle enfermée dans une tour possède une tresse dorée très longue." },
    { word: "LE VILAIN PETIT CANARD", hint: "Un oisillon différent des autres devient un magnifique oiseau blanc." },
    { word: "LA PETITE SIRÈNE", hint: "Une créature marine à queue écailleuse rêve de marcher sur la terre ferme." },
    { word: "LE ROI GRENOUILLE", hint: "Un amphibien vert aide une princesse à récupérer une boule tombée dans une source." },
    { word: "BOUCLE D'OR", hint: "Une fillette entre chez trois plantigrades et goûte leur repas dans la forêt." },
    { word: "LES TROIS PETITS COCHONS", hint: "Des frères construisent des abris de paille, de bois et de brique contre un souffle puissant." },
    { word: "LE CHAT BOTTÉ", hint: "Un félin astucieux porte des souliers élégants pour aider son maître meunier." },
    { word: "POUCETTE", hint: "Une fillette pas plus haute qu'un doigt naît dans une fleur et rencontre un hanneton." },
    { word: "LA REINE DES NEIGES", hint: "Une souveraine au pouvoir glacé crée un palais de glace et lance des flocons." },
    { word: "ALADIN", hint: "Un garçon trouve un tapis volant et une lampe magique renfermant un esprit." },
    { word: "LE LIVRE DE LA JUNGLE", hint: "Un petit d'homme élevé par des loups se promène dans la forêt avec un ours et une panthère." },
    { word: "PINOCCHIO", hint: "Un pantin de bois dont le nez s'allonge quand il ne dit pas la vérité." },
    { word: "PETER PAN", hint: "Un garçon qui vole avec de la poudre scintillante et refuse de devenir grand." },
    { word: "LE BONHOMME DE PAIN D'ÉPICES", hint: "Une friandise qui prend vie, court dans la campagne et crie qu'on ne peut l'attraper." },
    { word: "JACK ET LE HARICOT MAGIQUE", hint: "Un jeune homme échange une vache contre des graines qui poussent jusqu'au ciel." },
    { word: "LA BELLE ET LA BÊTE", hint: "Une jeune fille intelligente brise le sort d'un prince à l'apparence monstrueuse." },
    { word: "LE PETIT CHEVAL BOSSU", hint: "Un petit destrier au dos bombé aide un jeune paysan à accomplir des tâches impossibles." },
    { word: "LA PRINCESSE AU PETIT POIS", hint: "Une jeune femme à la peau sensible sent un minuscule légume sous vingt matelas." },
    { word: "LES MUSICIENS DE BRÊME", hint: "Des animaux vieillissants partent en ville pour devenir artistes et rencontrent des voleurs." },
    { word: "LE LOUP ET LES SEPT CHEVREAUX", hint: "Un animal gris tente d'entrer dans une maison en adoucissant sa voix pour tromper les petits." },
    { word: "LE VAISSEAU FANTÔME", hint: "Un navire hanté condamné à errer sur les mers, avec un capitaine spectral." },
    { word: "POUF LE DRAGON", hint: "Une chanson qui raconte l'histoire d'un animal cracheur de feu imaginaire dans une grotte." },
    { word: "LA FÉE DES DENTS", hint: "Une créature ailée qui récupère les quenottes de lait sous l'oreiller en échange d'une pièce." },
    { word: "LE GÉANT DE ZÉRALDA", hint: "Un ogre qui capture les enfants rencontre une petite fille qui sait cuisiner." },

    // ====== TÉLÉVISION POUR ENFANTS (Παιδική Τηλεόραση - 25) ======
    { word: "BOB L'ÉPONGE", hint: "Un personnage jaune vit dans un ananas au fond de l'océan et prépare des galettes de crabe." },
    { word: "DORA L'EXPLORATRICE", hint: "Une fillette voyage avec un plan dans un sac à dos et demande de l'aide pour ses aventures." },
    { word: "PEPPA PIG", hint: "Une petite truie adore sauter dans les flaques de boue avec son frère George." },
    { word: "SAM LE POMPIER", hint: "Un courageux sauveteur en uniforme rouge aide les habitants d'une petite ville." },
    { word: "LES MYSTÉRIEUSES CITÉS D'OR", hint: "Un dessin animé d'aventure qui suit des enfants à la recherche de trésors légendaires." },
    { word: "WINNIE L'OURSON", hint: "Un plantigrade jaune, amateur de miel, vit dans une forêt avec ses amis en peluche." },
    { word: "TROTRO", hint: "Un petit âne gris espiègle qui refuse souvent de faire ce qu'on lui demande." },
    { word: "PETIT OURS BRUN", hint: "Un ourson mignon vit de petites aventures quotidiennes avec ses parents." },
    { word: "T'CHOUPI", hint: "Un jeune manchot curieux qui découvre le monde avec son doudou." },
    { word: "OUI-OUI", hint: "Un pantin de bois au chapeau rouge qui conduit un taxi au Pays des Jouets." },
    { word: "LES SCHTROUMPFS", hint: "De minuscules créatures bleues vivent dans un village de champignons, pourchassées par un sorcier." },
    { word: "LUCKY LUKE", hint: "Un cow-boy solitaire qui tire plus vite que son ombre et poursuit les bandits." },
    { word: "ASTÉRIX", hint: "Un petit guerrier gaulois résiste aux Romains grâce à une potion qui donne une force incroyable." },
    { word: "OBÉLIX", hint: "Le compagnon fort et gourmand du guerrier gaulois, toujours prêt à porter des menhirs." },
    { word: "TINTIN", hint: "Un reporter à la houppette parcourt le monde avec son fidèle compagnon canin blanc." },
    { word: "CAPITAINE CRAWL", hint: "Le marin colérique qui répète sans cesse « mille millions de mille sabords ! »." },
    { word: "LE MANÈGE ENCHANTÉ", hint: "Une série où un chien, un escargot et un lapin rose vivent dans un jardin magique." },
    { word: "MIRACULOUS", hint: "Deux étudiants parisiens se transforment en super-héros masqués pour protéger leur ville." },
    { word: "LADYBUG", hint: "L'héroïne au costume rouge à pois noirs qui combat le mal avec un yoyo magique." },
    { word: "MARTIN MATIN", hint: "Un garçon qui se lève chaque jour avec une nouvelle apparence et vit des histoires farfelues." },
    { word: "CÉSAR ET CAPUCINE", hint: "Deux enfants voyagent dans un tableau magique pour résoudre des problèmes." },
    { word: "DIDOU", hint: "Un lapin blanc qui dessine des objets qui prennent vie pour aider ses amis." },
    { word: "ZOUBIDA", hint: "Un personnage joyeux enseigne la musique et le rythme aux tout-petits avec des comptines." },
    { word: "PAT'PATROUILLE", hint: "Une équipe de chiots sauveteurs menée par un garçon nommé Ryder dans un port." },
    { word: "L'ÂNE TROTRO", hint: "Un bourricot espiègle qui vit de petites histoires drôles dans sa ferme." },

    // ====== CHANSONS ENFANTINES (Παιδικά Τραγούδια - 20) ======
    { word: "FRÈRE JACQUES", hint: "Une chanson qui demande si on dort encore et si les cloches sonnent les matines." },
    { word: "AU CLAIR DE LA LUNE", hint: "Une mélodie nocturne où l'on va chez la voisine pour chercher une plume et du feu." },
    { word: "UNE SOURIS VERTE", hint: "Une comptine où un petit rongeur est attrapé par la queue et trempé dans l'huile." },
    { word: "PIR-OUILLI", hint: "Une chanson joyeuse sur un petit oiseau qui fait des bonds sur une branche." },
    { word: "SUR LE PONT D'AVIGNON", hint: "Un chant où l'on danse en rond en imitant les gestes des lavandières et des messieurs." },
    { word: "À LA CLAIRE FONTAINE", hint: "Une romance mélancolique sur un rossignol perdu et une rose blanche refusée." },
    { word: "IL PLEUT, IL PLEUT, BERGÈRE", hint: "Une chanson qui invite une gardienne de troupeaux à se mettre à l'abri pendant l'averse." },
    { word: "SACRÉ CHARLEMAGNE", hint: "Un air ironique sur un célèbre empereur qui aurait inventé l'école et les devoirs." },
    { word: "CADET ROUSSELLE", hint: "Un personnage à l'habit troué et au chapeau à cornes qui ne paye pas ses dettes." },
    { word: "MEUNIER, TU DORS", hint: "On chante pour réveiller un homme qui travaille avec le vent et la farine." },
    { word: "COUCOU, HIBOU", hint: "Une comptine où un oiseau nocturne chante dans la forêt pendant que l'enfant dort." },
    { word: "LE RENARD ET LA CIGOGNE", hint: "Une fable chantée sur un animal rusé et un échassier qui se rendent des visites à table." },
    { word: "LA MÈRE MICHEL", hint: "Une femme pleure son animal perdu sur le toit et un passant le lui rapporte." },
    { word: "MON BEAU SAPIN", hint: "Un chant de Noël célébrant un arbre toujours vert décoré de guirlandes." },
    { word: "IL ÉTAIT UN PETIT NAVIRE", hint: "Une chanson de marin où l'on menace de manger un matelot faute de biscuits." },
    { word: "DANS LA FORÊT LOINTAINE", hint: "On entend une chouette ululer au-dessus des grands arbres dans la nuit." },
    { word: "GENS DE LA VILLE", hint: "Une ronde enfantine sur un enfant qui cherche des amis pour jouer." },
    { word: "SAVEZ-VOUS PLANTER DES CHOUX", hint: "Une chansonnette où l'on enseigne à planter un légume avec le coude, le genou." },
    { word: "UN ÉLÉPHANT QUI SE BALANÇAIT", hint: "Un pachyderme joue sur une toile d'araignée puis appelle d'autres compagnons." },
    { word: "TOURNE, TOURNE, PETIT MOULIN", hint: "Une mélodie simple où l'on fait tourner les ailes d'un objet qui écrase le grain." },

    // ====== ÉCOLE ET MATERIEL (Σχολείο - 20) ======
    { word: "CARTABLE", hint: "Un sac porté sur le dos par les écoliers pour ranger leurs fournitures." },
    { word: "TROUSSE", hint: "Un étui avec une fermeture éclair où l'on range les stylos et les gommes." },
    { word: "ARDOISE", hint: "Une surface noire encadrée de bois sur laquelle on écrivait autrefois avec une craie." },
    { word: "CAHIER", hint: "Un ensemble de feuilles de papier reliées où les élèves prennent leurs notes." },
    { word: "RÉCRÉATION", hint: "Le moment de la journée scolaire où l'on peut sortir dans la cour pour jouer." },
    { word: "MAÎTRESSE", hint: "Une dame qui enseigne aux enfants la lecture et le calcul devant le tableau." },
    { word: "BIC", hint: "Un stylo à bille bon marché très utilisé pour écrire à l'encre bleue." },
    { word: "GOMME", hint: "Un petit objet en caoutchouc blanc ou rose qui efface les traces de crayon." },
    { word: "TAILLE-CRAYON", hint: "Un outil muni d'une lame pour rendre pointue l'extrémité d'un crayon de bois." },
    { word: "RÈGLE", hint: "Une barre graduée en plastique qui sert à mesurer et tracer des lignes droites." },
    { word: "COMPAS", hint: "Un instrument à deux branches qui sert à dessiner des cercles parfaits." },
    { word: "COLLE", hint: "Une substance liquide ou en bâton qui permet d'assembler deux feuilles de papier." },
    { word: "FEUTRE", hint: "Un stylo à pointe en fibre qui dépose une encre colorée pour faire des dessins." },
    { word: "CRAYON DE COULEUR", hint: "Un petit bâton de bois à la mine pigmentée pour faire des coloriages." },
    { word: "TABLEAU NOIR", hint: "Une grande plaque foncée fixée au mur où l'on écrit avec des craies." },
    { word: "ÉCOLE", hint: "Le bâtiment où les enfants vont chaque matin pour apprendre des choses nouvelles." },
    { word: "DEVOIRS", hint: "Les exercices que les professeurs donnent à faire à la maison après la journée de cours." },
    { word: "DICTÉE", hint: "Un exercice d'orthographe où l'on écrit des mots prononcés par l'enseignant." },
    { word: "BIBLIOTHÈQUE", hint: "Une pièce silencieuse remplie de livres que l'on peut emprunter pour lire." },
    { word: "CANTINE", hint: "La salle où les élèves prennent leur repas à midi, souvent avec un plateau." },

    // ====== HÉROS ET PERSONNAGES (Ήρωες - 25) ======
    { word: "SPIDER-MAN", hint: "Un justicier en costume d'araignée grimpe aux murs en lançant des fils." },
    { word: "BATMAN", hint: "Le chevalier noir protège sa cité avec des gadgets et une silhouette sombre." },
    { word: "SUPERMAN", hint: "Un homme très fort qui vole avec une cape rouge et craint les pierres vertes." },
    { word: "CAPITAINE AMERICA", hint: "Un soldat au bouclier rond défend la liberté après avoir reçu un sérum." },
    { word: "HULK", hint: "Un géant émeraude devient incroyablement puissant quand il se met en colère." },
    { word: "THOR", hint: "Le dieu du tonnerre brandit un marteau magique et voyage entre les mondes." },
    { word: "IRON MAN", hint: "Un inventeur milliardaire revêt une armure métallique volante pleine de technologie." },
    { word: "ELSA", hint: "Une reine capable de créer de la glace et des congères d'un geste de la main." },
    { word: "OLAF", hint: "Un bonhomme de neige enchanté qui rêve de voir l'été et les câlins chauds." },
    { word: "MOANA", hint: "Une jeune insulaire navigue sur l'océan pour rendre son cœur à une divinité." },
    { word: "ARIEL", hint: "La benjamine du roi des mers collectionne des artefacts terrestres dans une grotte." },
    { word: "SIMBA", hint: "Un jeune lionceau doit devenir le souverain de la savane après une tragédie." },
    { word: "MULAN", hint: "Une courageuse jeune fille s'habille en guerrier pour défendre sa patrie." },
    { word: "BELLE", hint: "Une jeune femme intelligente qui aime les histoires brise le sort d'un prince." },
    { word: "POCAHONTAS", hint: "Une princesse amérindienne parle aux esprits et protège la nature." },
    { word: "MERLIN L'ENCHANTEUR", hint: "Un vieux magicien barbu conseille le futur roi Arthur avec sagesse." },
    { word: "TARZAN", hint: "Un homme élevé par des grands singes se déplace en criant et en s'accrochant aux lianes." },
    { word: "ALICE", hint: "Une fillette tombe dans un terrier et rencontre un chapelier fou et une reine de cœur." },
    { word: "LE PETIT PRINCE", hint: "Un garçon blond venu d'un astéroïde demande qu'on lui dessine un mouton." },
    { word: "MAÎTRE YODA", hint: "Un petit être vert ridé enseigne la sagesse aux chevaliers dans une galaxie lointaine." },
    { word: "HARRY POTTER", hint: "Un jeune sorcier à lunettes fréquente une école de magie et combat un mage noir." },
    { word: "FIFIBRINDACIER", hint: "Une fée espiègle jalouse du bonheur des autres essaie de voler la voix d'une sirène." },
    { word: "WINNIE L'OURSON", hint: "Un plantigrade jaune amateur de miel vit dans une forêt avec ses amis en peluche." },
    { word: "PADDINGTON", hint: "Un plantigrade venu du Pérou avec une valise, amateur de confiture d'orange." },
    { word: "BOULE", hint: "Un petit garçon blond et son chien blanc vivent des aventures humoristiques." },

    // ====== ANIMAUX (Ζώα - 10) ======
    { word: "ÉLÉPHANT", hint: "Le plus grand mammifère terrestre avec une trompe et de grandes oreilles." },
    { word: "GIRAFE", hint: "Un animal au très long cou tacheté qui broute les feuilles des acacias." },
    { word: "CROCODILE", hint: "Un reptile aux dents pointues qui vit dans les rivières et les marais chauds." },
    { word: "DAUPHIN", hint: "Un mammifère marin joueur qui bondit hors des vagues et communique en sifflant." },
    { word: "PAPILLON", hint: "Un insecte aux ailes colorées qui se pose sur les fleurs après avoir été chenille." },
    { word: "COCHON D'INDE", hint: "Un petit rongeur domestique à poil court qui couine lorsqu'il a faim." },
    { word: "LAPIN", hint: "Un petit mammifère aux longues oreilles qui aime les carottes et creuse des terriers." },
    { word: "CHAT", hint: "Un félin domestique qui ronronne, chasse les souris et fait sa toilette avec sa langue." },
    { word: "CHIEN", hint: "Le meilleur ami de l'homme, fidèle, qui remue la queue et rapporte la balle." },
    { word: "POISSON ROUGE", hint: "Un petit animal aquatique orange qui nage dans un bocal ou un bassin." },

    // ====== JOUETS ET LOISIRS (Παιχνίδια - 10) ======
    { word: "POUPÉE", hint: "Un jouet ressemblant à un bébé, souvent habillé de vêtements miniatures, pour jouer à la maman." },
    { word: "VOITURE TÉLÉCOMMANDÉE", hint: "Un véhicule miniature que l'on dirige à distance avec une manette." },
    { word: "LÉGO", hint: "Des briques de plastique qui s'emboîtent pour construire des châteaux ou des vaisseaux." },
    { word: "BALANÇOIRE", hint: "Un siège suspendu par des cordes au parc où l'on monte et descend." },
    { word: "TOBOGGAN", hint: "Un grand plan incliné sur l'aire de jeux où l'on glisse assis." },
    { word: "BILLES", hint: "De petites sphères en verre coloré qu'on fait rouler dans un circuit dessiné au sol." },
    { word: "TRAIN ÉLECTRIQUE", hint: "Un circuit miniature avec des wagons qui roulent sur des rails grâce à une prise." },
    { word: "JEU DE SOCIÉTÉ", hint: "Une activité en famille autour d'une table avec un plateau, des dés et des pions." },
    { word: "DÉGUISEMENT", hint: "Un costume pour se transformer en princesse, pirate ou super-héros." },
    { word: "LIVRE", hint: "Un objet plein d'histoires et d'images que l'on feuillette avant de s'endormir." },

    // ====== NOURRITURE ET GOURMANDISES (Φαγητά - 10) ======
    { word: "CHOCOLAT", hint: "Une friandise brune et sucrée qui fond dans la bouche, fabriquée à partir de fèves." },
    { word: "BONBON", hint: "Une petite confiserie sucrée qui pique ou adoucit la langue, souvent colorée." },
    { word: "GLACE", hint: "Un dessert glacé que l'on lèche en cornet, surtout en été, à la fraise ou à la vanille." },
    { word: "CRÊPE", hint: "Une fine galette de pâte cuite à la poêle, que l'on garnit de sucre ou de confiture." },
    { word: "GAUFRETTE", hint: "Une pâtisserie croustillante aux motifs en carreaux, souvent saupoudrée de sucre glace." },
    { word: "PAIN AU CHOCOLAT", hint: "Une viennoiserie feuilletée contenant deux barres d'une pâte brune fondante." },
    { word: "COMPOTE", hint: "Une purée de fruits cuits, souvent de pommes, que l'on déguste dans un petit pot." },
    { word: "YAOURT", hint: "Un produit laitier crémeux, nature ou aux fruits, que l'on mange à la cuillère." },
    { word: "BISCUIT", hint: "Un petit gâteau sec à tremper dans un verre de lait ou une tasse de thé." },
    { word: "SIROP", hint: "Un liquide concentré et sucré que l'on dilue dans l'eau pour faire une boisson." }
];
