const SECRET_WORDS = [
    // ====== COLEGIO Y MATERIALES (Σχολείο - 30) ======
    { word: "MOCHILA", hint: "Una bolsa grande que los alumnos llevan en los hombros para cargar utilidades." },
    { word: "ESTUCHE", hint: "Un objeto pequeño con cremallera donde se guardan los lápices y las gomas." },
    { word: "RECREO", hint: "El momento más divertido del día escolar donde se puede salir al patio a jugar." },
    { word: "COLEGIO", hint: "El edificio donde los niños van cada mañana para aprender cosas nuevas." },
    { word: "PROFESOR", hint: "La persona que se coloca frente a la clase y enseña a leer y escribir." },
    { word: "VACACIONES", hint: "Los meses de verano donde no hay clases y se puede ir a la playa." },
    { word: "LAPIZ", hint: "Un utensilio de madera con una punta oscura que sirve para escribir." },
    { word: "PIZARRA", hint: "Una superficie grande en la pared de la clase donde se escribe con tiza." },
    { word: "CUADERNO", hint: "Un objeto con hojas de papel unidas donde los niños apuntan las tareas." },
    { word: "LIBRO", hint: "Un objeto lleno de páginas con historias o dibujos que leemos en la biblioteca." },
    { word: "GOMA", hint: "Un objeto pequeño que sirve para borrar los fallos al escribir." },
    { word: "REGLA", hint: "Una herramienta recta de plástico que sirve para medir centímetros." },
    { word: "TIJERAS", hint: "Un utensilio de dos hojas metálicas que sirve para cortar papel." },
    { word: "PEGAMENTO", hint: "Un líquido o barra pastosa que sirve para unir trozos de cartulina." },
    { word: "SACAPUNTAS", hint: "Un objeto pequeño con una cuchilla que sirve para afilar la mina." },
    { word: "PATIO", hint: "La zona exterior del centro escolar donde los niños corren y juegan." },
    { word: "PINTURAS", hint: "Lápices de muchos colores que se usan para rellenar dibujos." },
    { word: "GIMNASIO", hint: "Una sala grande dentro del centro escolar donde se hacen deportes." },
    { word: "SILLA", hint: "Mueble con cuatro patas que sirve para sentarse frente al pupitre." },
    { word: "MESA", hint: "Mueble con superficie plana donde los alumnos apoyan sus libretas." },
    { word: "TIZA", hint: "Barrita de arcilla blanca o de colores que se usa para escribir en el encerado." },
    { word: "MAPA", hint: "Un dibujo grande que muestra los países, ríos y montañas del mundo." },
    { word: "DICCIONARIO", hint: "Un volumen gordo que explica el significado de todas las expresiones." },
    { word: "ALUMNO", hint: "Un niño o niña que asiste a clase para recibir educación." },
    { word: "TAREA", hint: "Trabajo que los profesores mandan para hacer en casa por la tarde." },
    { word: "EXAMEN", hint: "Una prueba en papel para ver cuánto han aprendido los estudiantes." },
    { word: "BIBLIOTECA", hint: "Una sala silenciosa llena de estanterías con relatos listos para leer." },
    { word: "PUPITRE", hint: "Mueble escolar para sentarse que incluye una superficie para escribir." },
    { word: "HORARIO", hint: "Una lista que muestra qué asignaturas toca estudiar cada día." },
    { word: "ROTULADOR", hint: "Bolígrafo con punta de fieltro que sirve para pintar con trazos gruesos." },

    // ====== TRADICIONES Y CUENTOS (Παραμύθια - 30) ======
    { word: "RATONCITO PEREZ", hint: "Un pequeño animal que se lleva los de leche por la noche y deja monedas." },
    { word: "REYES MAGOS", hint: "Tres personajes mágicos que traen regalos en camello la noche del cinco de enero." },
    { word: "CAPERUCITA ROJA", hint: "Una niña con una prenda de abrigo de color vivo que visita a su abuela." },
    { word: "CENICIENTA", hint: "Una joven que pierde un zapato de cristal en el palacio antes de la medianoche." },
    { word: "BLANCANIEVES", hint: "Una princesa que vive con siete amigos pequeños y muerde una fruta envenenada." },
    { word: "DON QUIJOTE", hint: "Un famoso caballero de la literatura que confunde los molinos con gigantes." },
    { word: "PINOCHO", hint: "Un muñeco de madera al que le crece la nariz cuando no dice la verdad." },
    { word: "PETER PAN", hint: "El niño que vuela con polvo mágico y nunca quiere crecer." },
    { word: "RAPUNZEL", hint: "Una princesa encerrada en una estructura de piedra que tiene un cabello dorado larguísimo." },
    { word: "BELLA DURMIENTE", hint: "Una hermosa joven que se pincha el dedo con una rueca y duerme cien años." },
    { word: "EL PATITO FEO", hint: "Un ave que nace diferente a sus hermanos pero se convierte en un hermoso cisne." },
    { word: "HANSEL Y GRETEL", hint: "Dos hermanos que encuentran una casa hecha de dulces en el bosque." },
    { word: "LOS TRES CERDITOS", hint: "Hermanos animales que construyen viviendas de paja, madera y ladrillo." },
    { word: "EL GATO CON BOTAS", hint: "Un felino astuto que lleva calzado elegante para ayudar a su dueño." },
    { word: "ALADINO", hint: "Un chico que encuentra una alfombra voladora y una lámpara con un genio." },
    { word: "SIRENITA", hint: "Una joven del océano con cola de pez que quiere tener piernas humanas." },
    { word: "HADAS", hint: "Pequeñas criaturas fantásticas con alas que usan varitas para cumplir deseos." },
    { word: "DUENDE", hint: "Un ser fantástico muy pequeño con orejas puntiagudas que esconde tesoros." },
    { word: "GIGANTE", hint: "Un personaje de gran tamaño que aparece en historias de aventuras." },
    { word: "BRUJA", hint: "Una mujer de los relatos que vuela en escoba y prepara pociones." },
    { word: "TESORO", hint: "Un cofre lleno de monedas de oro escondido en una isla remota." },
    { word: "MAGIA", hint: "Poder fantástico que permite hacer trucos imposibles o volar." },
    { word: "REINO", hint: "El territorio gobernado por una familia real dentro de un relato." },
    { word: "PRINCIPE", hint: "El hijo de los gobernantes del castillo que busca a su pareja ideal." },
    { word: "REY", hint: "El gobernante principal de un territorio que lleva corona de oro." },
    { word: "REINA", hint: "La madre o gobernante del territorio que se sienta en el trono." },
    { word: "CASTILLO", hint: "Un edificio enorme de piedra con altas torres donde vive la realeza." },
    { word: "ALFOMBRA", hint: "Un objeto de tela que cubre el suelo, pero en Oriente sirve para viajar por el aire." },
    { word: "VARITA", hint: "Un bastón corto de madera que usan los seres mágicos para hacer hechizos." },
    { word: "POCION", hint: "Un líquido preparado en un caldero que produce efectos fantásticos." },

    // ====== CANCIONES INFANTILES (Παιδικά Τραγούδια - 30) ======
    { word: "EL COCHECITO LERE", hint: "Una melodía popular sobre un vehículo que dice lere y la niña no sube." },
    { word: "LA VACA LOLA", hint: "Un tema sobre un animal del campo que tiene cabeza, cola y hace muuu." },
    { word: "SUSANITA", hint: "Un tema muy conocido sobre una niña que tiene un ratón que come chocolate." },
    { word: "LOS POLLITOS", hint: "La melodía que cantan los niños cuando las aves dicen pío pío." },
    { word: "AL DON PIRULERO", hint: "Un juego musical donde cada participante imita el sonido de un instrumento." },
    { word: "CUCU CANTABA", hint: "Un tema tradicional sobre un animal verde que canta debajo del agua." },
    { word: "EL PATIO DE MI CASA", hint: "Una melodía tradicional que dice que este lugar es particular." },
    { word: "PING PONG", hint: "Un muñeco de cartón que se lava la carita con agua y con jabón." },
    { word: "UN ELEFANTE", hint: "Una melodía para contar donde un gran animal se balanceaba en una telaraña." },
    { word: "ESTRELLITA", hint: "Una nana clásica sobre un cuerpo brillante en el cielo nocturno." },
    { word: "CHUCHUWA", hint: "Un baile muy movido donde se estiran los brazos, los puños y los pies." },
    { word: "ARROZ CON LECHE", hint: "Una melodía antigua sobre un postre que sirve para cantar con quién casarse." },
    { word: "LA TARARA", hint: "Un tema tradicional sobre una mujer que baila con su vestido de seda." },
    { word: "MAMBRU", hint: "Una melodía infantil sobre un señor que se fue a una misión y no regresará." },
    { word: "DON GATO", hint: "Un tema sobre un felino en el tejado que cae por mirar a una gata." },
    { word: "DEBAJO UN BOTON", hint: "Una melodía corta sobre lo que encontró Martín: un ratón chiquitín." },
    { word: "EN LA COCHERA", hint: "Un tema sobre un coche pequeño que hace toc toc al andar." },
    { word: "SOY UNA TAZA", hint: "Un tema moderno muy bailable sobre utensilios de cocina como una tetera." },
    { word: "LA GALLINA TURULECA", hint: "Una divertida melodía sobre un ave que ha puesto uno, dos y tres huevos." },
    { word: "HOLA DON PEPITO", hint: "Un diálogo cantado entre dos señores que se saludan al cruzarse por la calle." },
    { word: "LA MANE", hint: "Un tema donde se pone una extremidad aquí y otra allá siguiendo el ritmo." },
    { word: "TALLARIN", hint: "Un tema sobre un fideo largo que se mueve por el cuerpo con un poco de aceite." },
    { word: "EL AUTO DE PAPA", hint: "Una melodía sobre viajar en un vehículo familiar cantando pi pi pi." },
    { word: "PINOCHO MALUCHO", hint: "Un cantar sobre el muñeco de madera que fue a la clínica por un dolor." },
    { word: "UN BARQUITO CHIQUITITO", hint: "Una historia cantada sobre una embarcación pequeña que no podía navegar." },
    { word: "EL RATON VAQUERO", hint: "Un cantar sobre un roedor con sombrero y herramientas de juguete que habla inglés." },
    { word: "TENGO UNA VACA LECHERA", hint: "Una melodía sobre un animal del prado que da un producto muy dulce." },
    { word: "CINCO LOBITOS", hint: "Una nana tradicional que se canta moviendo las manos para contar crías." },
    { word: "LA CHIVITA", hint: "Un cantar acumulativo sobre sacar a un animal testarudo de su sitio." },
    { word: "EL BAILE DE LOS PAJARITOS", hint: "Una melodía muy alegre donde todos imitan el vuelo y el pico de las aves." },

    // ====== HEROES Y PERSONAJES (Ήρωες - 30) ======
    { word: "SPIDERMAN", hint: "Un héroe con traje de arácnido que trepa paredes usando hilos sedosos." },
    { word: "BATMAN", hint: "El caballero de la noche que protege su ciudad con herramientas y vehículos oscuros." },
    { word: "SUPERMAN", hint: "Un hombre muy fuerte que vuela, lleva capa y teme a los minerales verdes." },
    { word: "IRON MAN", hint: "Un inventor millonario con una armadura metálica que vuela y tiene luces." },
    { word: "HULK", hint: "Un gigante de color esmeralda que se vuelve muy fuerte cuando se enfada." },
    { word: "ELSA", hint: "Una reina con poderes de congelación que crea palacios invernales." },
    { word: "OLAF", hint: "Un ser de nieve creado por magia al que le encantan los abrazos cálidos." },
    { word: "BUZZ LIGHTYEAR", hint: "Un astronauta de juguete que viaja hasta el infinito y más allá." },
    { word: "WOODY", hint: "Un comisario de trapo con sombrero que cuida a todos los juguetes del cuarto." },
    { word: "RAYO MCQUEEN", hint: "Un coche de carreras veloz con el número noventa y cinco que busca ganar la copa." },
    { word: "THOR", hint: "Un príncipe del trueno que vuela y lanza una herramienta muy pesada." },
    { word: "CAPITAN AMERICA", hint: "Un soldado con un escudo redondo que lucha por la justicia." },
    { word: "AQUAMAN", hint: "Un personaje del océano que puede hablar con los peces y vive bajo el agua." },
    { word: "FLASH", hint: "El hombre más rápido del mundo que viste un traje con un rayo amarillo." },
    { word: "BATCHICA", hint: "Una heroína joven con capa que ayuda al hombre murciélago a vigilar los tejados." },
    { word: "SUPERCHICA", hint: "La prima del hombre de acero que comparte sus mismos poderes de vuelo." },
    { word: "ROBIN", hint: "El joven compañero del caballero oscuro que viste un traje de colores." },
    { word: "GROOT", hint: "Un aliado con forma de planta grande que solo sabe decir su propio nombre." },
    { word: "MOANA", hint: "Una joven isleña que navega por el océano para devolver el corazón de una deidad." },
    { word: "TARZAN", hint: "Un hombre criado por simios en la selva que se desplaza usando lianas." },
    { word: "HERCULES", hint: "Un joven con una fuerza increíble, hijo de mitos griegos, que realiza grandes hazañas." },
    { word: "MAUI", hint: "Un gran semidiós del océano con un anzuelo mágico que cambia de forma." },
    { word: "SIMBA", hint: "Un pequeño cachorro felino que debe convertirse en el líder de la sabana." },
    { word: "MULAN", hint: "Una valiente joven que se viste de guerrero para defender a su familia." },
    { word: "BELLA", hint: "Una joven inteligente que ama la lectura y rompe el hechizo de un príncipe." },
    { word: "POCAHONTAS", hint: "Una joven nativa que ama la naturaleza y habla con los espíritus del bosque." },
    { word: "MERIDA", hint: "Una princesa experta con el arco y las flechas que cambia su propio destino." },
    { word: "TIANA", hint: "Una joven cocinera que besa a un sapo y se transforma en un anfibio verde." },
    { word: "JASMINE", hint: "La hija del sultán que viaja junto a su amor en una superficie voladora." },
    { word: "ARIEL", hint: "La hija menor del rey del mar que colecciona objetos humanos en su cueva." },

    // ====== DIBUJOS ANIMADOS Y SERIES (Κινούμενα Σχέδια - 30) ======
    { word: "POCOYO", hint: "Un niño con gorro que descubre el mundo junto a un pato y una elefanta rosa." },
    { word: "TADEO JONES", hint: "Un obrero que sueña con la arqueología y termina viviendo aventuras." },
    { word: "DORAEMON", hint: "Un robot felino del futuro que ayuda a su amigo con inventos de su barriga." },
    { word: "BOB ESPONJA", hint: "Un personaje marino que cocina hamburguesas y vive en una piña." },
    { word: "PATRULLA CANINA", hint: "Un grupo de cachorros rescatistas liderados por un niño llamado Ryder." },
    { word: "PEPPA PIG", hint: "Una cerdita que vive con su hermano George y adora saltar en el lodo." },
    { word: "MICKEY MOUSE", hint: "El ratón más famoso del mundo que lleva pantalones rojos y guantes blancos." },
    { word: "BLUEY", hint: "Una perrita australiana que inventa juegos creativos con su hermana Bingo." },
    { word: "POKEMON", hint: "Criaturas de bolsillo que evolucionan y luchan para sus entrenadores." },
    { word: "SHREK", hint: "Un gran ser verde que vive feliz en su ciénaga hasta que salva a una princesa." },
    { word: "NINJAGO", hint: "Guerreros ninja hechos de bloques de plástico que protegen su entorno." },
    { word: "MIRACULOUS", hint: "Dos estudiantes de París que se transforman en defensores secretos con antifaz." },
    { word: "LADYBUG", hint: "Una heroína con traje rojo y puntos negros que combate el mal con un yo-yo." },
    { word: "SONIC", hint: "Un erizo azul de los videojuegos que salta y gira a gran velocidad." },
    { word: "SCOOBY DOO", hint: "Un gran canino marrón miedoso que resuelve misterios junto a sus amigos." },
    { word: "TOM Y JERRY", hint: "Las eternas persecuciones entre un felino gris y un pequeño roedor." },
    { word: "LOONEY TUNES", hint: "Cortos animados que incluyen a un conejo de la suerte y a un pato inquieto." },
    { word: "LOS SIMPSON", hint: "Una famosa familia americana de color amarillo que vive en Springfield." },
    { word: "POPEYE", hint: "Un marinero que gana una fuerza increíble cada vez que come vegetales de lata." },
    { word: "DORA EXPLORADORA", hint: "Una niña que viaja con un mapa en su mochila y pide ayuda en sus rutas." },
    { word: "HEIDI", hint: "Una niña que vive feliz con su abuelo en una cabaña de los Alpes." },
    { word: "MARCO", hint: "Un niño italiano que viaja en barco por Sudamérica buscando a su madre." },
    { word: "BEN 10", hint: "Un chico que encuentra un reloj espacial que le permite transformarse en alienígenas." },
    { word: "GUMBALL", hint: "Un felino azul que asiste a una escuela loca junto a su hermano pez Darwin." },
    { word: "PHINEAS Y FERB", hint: "Dos hermanos que construyen inventos gigantescos en su jardín durante el verano." },
    { word: "BOB CONSTRUCTOR", hint: "Un obrero amable que arregla la ciudad con máquinas parlantes." },
    { word: "CAILLOU", hint: "Un niño pequeño de cuatro años que aprende lecciones cotidianas en su hogar." },
    { word: "SAM EL BOMBERO", hint: "Un valiente apagafuegos que rescata a los vecinos de un pequeño pueblo." },
    { word: "PJ MASKS", hint: "Tres niños que se ponen sus prendas nocturnas para convertirse en héroes." },
    { word: "BARRIO SESAMO", hint: "Un vecindario infantil habitado por marionetas famosas como Elmo." }
];
